### ISSUE TITLE
(CLOSED) Evo 1.1RC2 - DocLister Snippet

### ISSUE THREAD

**Issue by modxuser** [modxcms/evolution#462]
Where can I find the English documentation ?

**Comment by janniconl** [comment]
https://github.com/AgelxNash/DocLister

http://modx.im/blog/docs/2676.html

Translated to English:
https://translate.googleusercontent.com/translate_c?depth=1&hl=nl&ie=UTF8&prev=_t&rurl=translate.google.nl&sl=ru&tl=en&u=https://github.com/AgelxNash/DocLister&usg=ALkJrhh4oKzHr_53z-zN9CouWVsfZD0DZA

https://translate.google.nl/translate?sl=ru&tl=en&js=y&prev=_t&hl=nl&ie=UTF-8&u=http%3A%2F%2Fmodx.im%2Fblog%2Fdocs%2F2676.html&edit-text=

You could ask AgelxHash for support as well via GitHub

**Comment by modxuser** [comment]
So there is no official documentation other than in Russian ? The Google translation is rubbish

Also, the links found on that page dont for deoms etc. don't work

So far as I am aware DocLister is supposed to be a Ditto replacement - does it do all of the things that Ditto can ?

Pagination, Iteration, CountDocs, RSS feeds etc.

**Comment by janniconl** [comment]
Just posting what I could find mate. I'm not using this plugin, nor did I write it. 

If I where you I would continue using Ditto.. still works fine for me.

**Comment by modxuser** [comment]
I use Ditto, but it doesn't work properly with the new setting - "Use AliasListing only for Folders"

As can be read here: https://github.com/modxcms/evolution/issues/458

**Comment by janniconl** [comment]
Then in my opinion that bug should be fixed first, since 99% of all evo installations will probably use Ditto :)

**Comment by modxuser** [comment]
That's what I thought would happen, due to the amount of people using Ditto

I presume "dmi3yy" has a lot on his plate at the moment - he said he would try and look at the problem last week, but I don't know if that has happend yet

**Comment by dmi3yy** [comment]
Full DocLister Docs http://docs.evolution-cms.com/Extras/Snippets/DocLister
or the same on github https://github.com/evolution-cms/docs/tree/master/03_Extras/04_Snippets/DocLister

but All or Russian lang 

about Bug AL + Ditto not fixed yet

**Comment by modxuser** [comment]
Thanks for the feedback dmi3yy

I will look further into DocLister once the Ditto problem has been resolved

**Comment by kp52** [comment]
I have made a start on translating the DocLister documentation into English (index and parameters sections). I hope I will find time to continue with it, but don't hold your breath! Where can I share the files? This editor doesn't seem to let me upload them.

**Comment by modxuser** [comment]
@kp52 

Great stuff, thanks for your time and effort

Would it not be best to post on the RTFM: https://rtfm.modx.com/extras/evo/

**Comment by kp52** [comment]
Translation now on RTFM [https://rtfm.modx.com/extras/evo/doclister/](https://rtfm.modx.com/extras/evo/doclister/). Probably not 100% accurate - it's 10 years since I did any translating, and I don't use MODX any more. I had a brief go installing DocLister on Evo 1.1RC2 to check on a couple of things. A tad better than Google Translate, in any case.

**Comment by janniconl** [comment]
Great work! Thx!

**Comment by modxuser** [comment]
Great stuff - I will take a long look at the weekend and see if I can't break my site using it :)

@kp52 - Just out of interest, are you still using / developing Clipper

**Comment by Deesen** [comment]
If you opened an issue yourself, you can close it. There should be a button "Close Issue".

**Comment by modxuser** [comment]
Found it :)
