### ISSUE TITLE
YAMS doesn't show templates to assign in EVO 1.1

### ISSUE THREAD

**Issue by fourroses666** [modxcms/evolution#526]
Did a clean install Evo 1.1 and YAMS.
I can't assign any templates while there should show 2 templates.

I don't know when upgrading a YAMS site if there are issues but on a clean install it doesn't work for me.

![yamss](https://cloud.githubusercontent.com/assets/523389/13427552/18891b76-dfb5-11e5-956c-ecd07d5edca7.jpg)

**Comment by fourroses666** [comment]
I think it has to do with this new feature: 

_Template selectable when creating or editing ressources._

**Comment by Deesen** [comment]
I cannot imagine it has to do with this feature as YAMS does not recognize it. Which YAMS-version?

**Comment by fourroses666** [comment]
Newest version, which works on other sites. 
Also tried a version of the module from a site which also works.
I can give you access to the site if you would like to see whats going on.

**Comment by Deesen** [comment]
Yes direct access pls ;-). This latest version / ZIP? https://github.com/goldsky/YAMS

**Comment by fourroses666** [comment]
yea its a fork I have, I will email you

**Comment by Deesen** [comment]
YAMS is using deprecated functions. Will fork and update it soon.

**Comment by fourroses666** [comment]
Seen a deprecated issue here: https://github.com/goldsky/YAMS/issues/9

**Comment by Deesen** [comment]
https://github.com/Deesen/YAMS

**Comment by fourroses666** [comment]
cool, will try that.

**Comment by fourroses666** [comment]
Works, Thanks!! 

I will update my fork too.

**Comment by fourroses666** [comment]
Hmm, didn't check the tabs yet. There are still some issues. I have 6 of each TV :(
adding a new TV doesn't go to the tab.

_Failed to associate template variable pagetitle_en" with template number 3 .
Failed to associate template variable pagetitle_nl" with template number 3 ._
.. etc.

**Comment by Deesen** [comment]
Should work now https://github.com/Deesen/YAMS

**Comment by Deesen** [comment]
Lol... suddenly hidden treasures pop up.. the content of original-language gets duplicated to the newly assigned TVs... content -> content_en, longtitle -> longtitle_en .. only when they are empty, nothing gets overwritten .. :+1: :+1:

**Comment by fourroses666** [comment]
will have a look tomorrow :warning:

**Comment by fourroses666** [comment]
It works Dennis. :+1: :+1: 

I have tested on an other install because of the many duplicated TV's. 
_That happened when it wasn't fixed and I clicked on update a couple of times._

If I find any issues I let you know :page_with_curl: 

Thanks again.
